/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Document.java
 *
 * Created on Nov 3, 2009, 11:00:16 PM
 */

package document;

import org.marnen.hive.ViewUtilities;

/**
 *
 * @author marnen
 */
public class Document extends javax.swing.JFrame {

  /** Creates new form Document */
  public Document() {
      initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    scroll_pane = new javax.swing.JScrollPane();
    data_table = new javax.swing.JTable();
    menu_bar = new javax.swing.JMenuBar();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("document/Bundle"); // NOI18N
    setTitle(bundle.getString("Document.title")); // NOI18N

    scroll_pane.setViewportView(data_table);

    setJMenuBar(menu_bar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(scroll_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(scroll_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Document().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTable data_table;
  private javax.swing.JMenuBar menu_bar;
  private javax.swing.JScrollPane scroll_pane;
  // End of variables declaration//GEN-END:variables

}
