/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IntroWindow.java
 *
 * Created on Nov 29, 2009, 9:48:12 PM
 */

package intro_window;

import org.marnen.hive.ViewUtilities;

/**
 *
 * @author marnen
 */
public class IntroWindow extends javax.swing.JFrame {

  /** Creates new form IntroWindow */
  public IntroWindow() {
      initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenu2 = new javax.swing.JMenu();
    jLabel1 = new javax.swing.JLabel();
    jMenuBar2 = new javax.swing.JMenuBar();
    file_menu = new javax.swing.JMenu();
    file_new_menu_item = new javax.swing.JMenuItem();
    file_open_menu_item = new javax.swing.JMenuItem();

    jMenu1.setText("File");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("intro_window/Bundle"); // NOI18N
    setTitle(bundle.getString("appName")); // NOI18N

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText(bundle.getString("welcome")); // NOI18N

    java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("document/Bundle"); // NOI18N
    file_menu.setText(bundle1.getString("Document.file_menu.text")); // NOI18N
    file_menu.setLabel(bundle1.getString("FileMenu.text")); // NOI18N

    file_new_menu_item.setAccelerator(ViewUtilities.makeShortcut(java.awt.event.KeyEvent.VK_N));
    file_new_menu_item.setText(bundle1.getString("FileMenu.New")); // NOI18N
    file_menu.add(file_new_menu_item);

    file_open_menu_item.setAccelerator(ViewUtilities.makeShortcut(java.awt.event.KeyEvent.VK_O));
    file_open_menu_item.setText(bundle1.getString("FileMenu.Open")); // NOI18N
    file_menu.add(file_open_menu_item);

    jMenuBar2.add(file_menu);

    setJMenuBar(jMenuBar2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addContainerGap(11, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroWindow().setVisible(true);
            }
        });
    }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu file_menu;
  private javax.swing.JMenuItem file_new_menu_item;
  private javax.swing.JMenuItem file_open_menu_item;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuBar jMenuBar2;
  // End of variables declaration//GEN-END:variables

}
